using System;

namespace RESTful_API
{
    public class MessageRequestDetails
    {
        public MessageRequestObject[]? MsgRequestObjects { get; set; }

    }
    public class MessageReplyDetails
    {
        public MessageReplyObject[]? MsgReplyObjects { get; set; }
    }

    public class MessageRequestObject
    {
        public string? Id { get; set; }
        public string? Message { get; set; }
        public string? MessageId { get; set; }
        public string? MessageType { get; set; }
        public string? MessagePub { get; set; }
        public string? MessageExp { get; set; }

        public string? MessageFromSourceSystem7 { get; set; }
        public string? MessageFromSourceSystem8 { get; set; }
        public string? MessageFromSourceSystem9 { get; set; }
        public string? MessageFromSourceSystem10 { get; set; }
        public string? MessageFromSourceSystem11 { get; set; }
        public string? MessageFromSourceSystem12 { get; set; }
        public string? MessageFromSourceSystem13 { get; set; }
        public string? MessageFromSourceSystem14 { get; set; }
        public string? MessageFromSourceSystem15 { get; set; }
        public string? MessageFromSourceSystem16 { get; set; }
        public string? MessageFromSourceSystem17 { get; set; }
        public string? MessageFromSourceSystem18 { get; set; }
        public string? MessageFromSourceSystem19 { get; set; }
        public string? MessageFromSourceSystem20 { get; set; }
        public string? MessageFromSourceSystem21 { get; set; }
        public string? MessageFromSourceSystem22 { get; set; }
        public string? MessageFromSourceSystem23 { get; set; }
        public string? MessageFromSourceSystem24 { get; set; }
        public string? MessageFromSourceSystem25 { get; set; }
        public string? MessageFromSourceSystem26 { get; set; }
        public string? MessageFromSourceSystem27 { get; set; }
        public string? MessageFromSourceSystem28 { get; set; }
        public string? MessageFromSourceSystem29 { get; set; }
        public string? MessageFromSourceSystem30 { get; set; }
        public string? MessageFromSourceSystem31 { get; set; }
        public string? MessageFromSourceSystem32 { get; set; }
        public string? MessageFromSourceSystem33 { get; set; }
        public string? MessageFromSourceSystem34 { get; set; }
        public string? MessageFromSourceSystem35 { get; set; }
        public string? MessageFromSourceSystem36 { get; set; }
        public string? MessageFromSourceSystem37 { get; set; }
        public string? MessageFromSourceSystem38 { get; set; }
        public string? MessageFromSourceSystem39 { get; set; }
        public string? MessageFromSourceSystem40 { get; set; }
        public string? MessageFromSourceSystem41 { get; set; }
        public string? MessageFromSourceSystem42 { get; set; }
        public string? MessageFromSourceSystem43 { get; set; }
        public string? MessageFromSourceSystem44 { get; set; }
        public string? MessageFromSourceSystem45 { get; set; }
        public string? MessageFromSourceSystem46 { get; set; }
        public string? MessageFromSourceSystem47 { get; set; }
        public string? MessageFromSourceSystem48 { get; set; }
        public string? MessageFromSourceSystem49 { get; set; }
        public string? MessageFromSourceSystem50 { get; set; }
        public string? MessageFromSourceSystem51 { get; set; }
        public string? MessageFromSourceSystem52 { get; set; }
        public string? MessageFromSourceSystem53 { get; set; }
        public string? MessageFromSourceSystem54 { get; set; }
        public string? MessageFromSourceSystem55 { get; set; }
        public string? MessageFromSourceSystem56 { get; set; }
        public string? MessageFromSourceSystem57 { get; set; }
        public string? MessageFromSourceSystem58 { get; set; }
        public string? MessageFromSourceSystem59 { get; set; }
        public string? MessageFromSourceSystem60 { get; set; }
        public string? MessageFromSourceSystem61 { get; set; }
        public string? MessageFromSourceSystem62 { get; set; }
        public string? MessageFromSourceSystem63 { get; set; }
        public string? MessageFromSourceSystem64 { get; set; }
        public string? MessageFromSourceSystem65 { get; set; }
        public string? MessageFromSourceSystem66 { get; set; }
        public string? MessageFromSourceSystem67 { get; set; }
        public string? MessageFromSourceSystem68 { get; set; }
        public string? MessageFromSourceSystem69 { get; set; }
        public string? MessageFromSourceSystem70 { get; set; }
        public string? MessageFromSourceSystem71 { get; set; }
        public string? MessageFromSourceSystem72 { get; set; }
        public string? MessageFromSourceSystem73 { get; set; }
        public string? MessageFromSourceSystem74 { get; set; }
        public string? MessageFromSourceSystem75 { get; set; }
        public string? MessageFromSourceSystem76 { get; set; }
        public string? MessageFromSourceSystem77 { get; set; }
        public string? MessageFromSourceSystem78 { get; set; }
        public string? MessageFromSourceSystem79 { get; set; }
        public string? MessageFromSourceSystem80 { get; set; }
        public string? MessageFromSourceSystem81 { get; set; }
        public string? MessageFromSourceSystem82 { get; set; }
        public string? MessageFromSourceSystem83 { get; set; }
        public string? MessageFromSourceSystem84 { get; set; }
        public string? MessageFromSourceSystem85 { get; set; }
        public string? MessageFromSourceSystem86 { get; set; }
        public string? MessageFromSourceSystem87 { get; set; }
        public string? MessageFromSourceSystem88 { get; set; }
        public string? MessageFromSourceSystem89 { get; set; }
        public string? MessageFromSourceSystem90 { get; set; }
        public string? MessageFromSourceSystem91 { get; set; }
        public string? MessageFromSourceSystem92 { get; set; }
        public string? MessageFromSourceSystem93 { get; set; }
        public string? MessageFromSourceSystem94 { get; set; }
        public string? MessageFromSourceSystem95 { get; set; }
        public string? MessageFromSourceSystem96 { get; set; }
        public string? MessageFromSourceSystem97 { get; set; }
        public string? MessageFromSourceSystem98 { get; set; }
        public string? MessageFromSourceSystem99 { get; set; }
        public string? MessageFromSourceSystem100 { get; set; }
        public string? MessageFromSourceSystem101 { get; set; }
        public string? MessageFromSourceSystem102 { get; set; }
        public string? MessageFromSourceSystem103 { get; set; }
        public string? MessageFromSourceSystem104 { get; set; }
        public string? MessageFromSourceSystem105 { get; set; }
        public string? MessageFromSourceSystem106 { get; set; }
        public string? MessageFromSourceSystem107 { get; set; }
        public string? MessageFromSourceSystem108 { get; set; }
        public string? MessageFromSourceSystem109 { get; set; }
        public string? MessageFromSourceSystem110 { get; set; }
        public string? MessageFromSourceSystem111 { get; set; }
        public string? MessageFromSourceSystem112 { get; set; }
        public string? MessageFromSourceSystem113 { get; set; }
        public string? MessageFromSourceSystem114 { get; set; }
        public string? MessageFromSourceSystem115 { get; set; }
        public string? MessageFromSourceSystem116 { get; set; }
        public string? MessageFromSourceSystem117 { get; set; }
        public string? MessageFromSourceSystem118 { get; set; }
        public string? MessageFromSourceSystem119 { get; set; }
        public string? MessageFromSourceSystem120 { get; set; }
        public string? MessageFromSourceSystem121 { get; set; }
        public string? MessageFromSourceSystem122 { get; set; }
        public string? MessageFromSourceSystem123 { get; set; }
        public string? MessageFromSourceSystem124 { get; set; }
        public string? MessageFromSourceSystem125 { get; set; }
        public string? MessageFromSourceSystem126 { get; set; }
        public string? MessageFromSourceSystem127 { get; set; }
        public string? MessageFromSourceSystem128 { get; set; }
        public string? MessageFromSourceSystem129 { get; set; }
        public string? MessageFromSourceSystem130 { get; set; }
        public string? MessageFromSourceSystem131 { get; set; }
        public string? MessageFromSourceSystem132 { get; set; }
        public string? MessageFromSourceSystem133 { get; set; }
        public string? MessageFromSourceSystem134 { get; set; }
        public string? MessageFromSourceSystem135 { get; set; }
        public string? MessageFromSourceSystem136 { get; set; }
        public string? MessageFromSourceSystem137 { get; set; }
        public string? MessageFromSourceSystem138 { get; set; }
        public string? MessageFromSourceSystem139 { get; set; }
        public string? MessageFromSourceSystem140 { get; set; }
        public string? MessageFromSourceSystem141 { get; set; }
        public string? MessageFromSourceSystem142 { get; set; }
        public string? MessageFromSourceSystem143 { get; set; }
        public string? MessageFromSourceSystem144 { get; set; }
        public string? MessageFromSourceSystem145 { get; set; }
        public string? MessageFromSourceSystem146 { get; set; }
        public string? MessageFromSourceSystem147 { get; set; }
        public string? MessageFromSourceSystem148 { get; set; }
        public string? MessageFromSourceSystem149 { get; set; }
        public string? MessageFromSourceSystem150 { get; set; }
        public string? MessageFromSourceSystem151 { get; set; }
        public string? MessageFromSourceSystem152 { get; set; }
        public string? MessageFromSourceSystem153 { get; set; }
        public string? MessageFromSourceSystem154 { get; set; }
        public string? MessageFromSourceSystem155 { get; set; }
        public string? MessageFromSourceSystem156 { get; set; }
        public string? MessageFromSourceSystem157 { get; set; }
        public string? MessageFromSourceSystem158 { get; set; }
        public string? MessageFromSourceSystem159 { get; set; }
        public string? MessageFromSourceSystem160 { get; set; }
        public string? MessageFromSourceSystem161 { get; set; }
        public string? MessageFromSourceSystem162 { get; set; }
        public string? MessageFromSourceSystem163 { get; set; }
        public string? MessageFromSourceSystem164 { get; set; }
        public string? MessageFromSourceSystem165 { get; set; }
        public string? MessageFromSourceSystem166 { get; set; }
        public string? MessageFromSourceSystem167 { get; set; }
        public string? MessageFromSourceSystem168 { get; set; }
        public string? MessageFromSourceSystem169 { get; set; }
        public string? MessageFromSourceSystem170 { get; set; }
        public string? MessageFromSourceSystem171 { get; set; }
        public string? MessageFromSourceSystem172 { get; set; }
        public string? MessageFromSourceSystem173 { get; set; }
        public string? MessageFromSourceSystem174 { get; set; }
        public string? MessageFromSourceSystem175 { get; set; }
        public string? MessageFromSourceSystem176 { get; set; }
        public string? MessageFromSourceSystem177 { get; set; }
        public string? MessageFromSourceSystem178 { get; set; }
        public string? MessageFromSourceSystem179 { get; set; }
        public string? MessageFromSourceSystem180 { get; set; }
        public string? MessageFromSourceSystem181 { get; set; }
        public string? MessageFromSourceSystem182 { get; set; }
        public string? MessageFromSourceSystem183 { get; set; }
        public string? MessageFromSourceSystem184 { get; set; }
        public string? MessageFromSourceSystem185 { get; set; }
        public string? MessageFromSourceSystem186 { get; set; }
        public string? MessageFromSourceSystem187 { get; set; }
        public string? MessageFromSourceSystem188 { get; set; }
        public string? MessageFromSourceSystem189 { get; set; }
        public string? MessageFromSourceSystem190 { get; set; }
        public string? MessageFromSourceSystem191 { get; set; }
        public string? MessageFromSourceSystem192 { get; set; }
        public string? MessageFromSourceSystem193 { get; set; }
        public string? MessageFromSourceSystem194 { get; set; }
        public string? MessageFromSourceSystem195 { get; set; }
        public string? MessageFromSourceSystem196 { get; set; }
        public string? MessageFromSourceSystem197 { get; set; }
        public string? MessageFromSourceSystem198 { get; set; }
        public string? MessageFromSourceSystem199 { get; set; }
        public string? MessageFromSourceSystem200 { get; set; }
        public string? MessageFromSourceSystem201 { get; set; }
        public string? MessageFromSourceSystem202 { get; set; }
        public string? MessageFromSourceSystem203 { get; set; }
        public string? MessageFromSourceSystem204 { get; set; }
        public string? MessageFromSourceSystem205 { get; set; }
        public string? MessageFromSourceSystem206 { get; set; }
        public string? MessageFromSourceSystem207 { get; set; }
        public string? MessageFromSourceSystem208 { get; set; }
        public string? MessageFromSourceSystem209 { get; set; }
        public string? MessageFromSourceSystem210 { get; set; }
        public string? MessageFromSourceSystem211 { get; set; }
        public string? MessageFromSourceSystem212 { get; set; }
        public string? MessageFromSourceSystem213 { get; set; }
        public string? MessageFromSourceSystem214 { get; set; }
        public string? MessageFromSourceSystem215 { get; set; }
        public string? MessageFromSourceSystem216 { get; set; }
        public string? MessageFromSourceSystem217 { get; set; }
        public string? MessageFromSourceSystem218 { get; set; }
        public string? MessageFromSourceSystem219 { get; set; }
        public string? MessageFromSourceSystem220 { get; set; }
        public string? MessageFromSourceSystem221 { get; set; }
        public string? MessageFromSourceSystem222 { get; set; }
        public string? MessageFromSourceSystem223 { get; set; }
        public string? MessageFromSourceSystem224 { get; set; }
        public string? MessageFromSourceSystem225 { get; set; }
        public string? MessageFromSourceSystem226 { get; set; }
        public string? MessageFromSourceSystem227 { get; set; }
        public string? MessageFromSourceSystem228 { get; set; }
        public string? MessageFromSourceSystem229 { get; set; }
        public string? MessageFromSourceSystem230 { get; set; }
        public string? MessageFromSourceSystem231 { get; set; }
        public string? MessageFromSourceSystem232 { get; set; }
        public string? MessageFromSourceSystem233 { get; set; }
        public string? MessageFromSourceSystem234 { get; set; }
        public string? MessageFromSourceSystem235 { get; set; }
        public string? MessageFromSourceSystem236 { get; set; }
        public string? MessageFromSourceSystem237 { get; set; }
        public string? MessageFromSourceSystem238 { get; set; }
        public string? MessageFromSourceSystem239 { get; set; }
        public string? MessageFromSourceSystem240 { get; set; }
        public string? MessageFromSourceSystem241 { get; set; }
        public string? MessageFromSourceSystem242 { get; set; }
        public string? MessageFromSourceSystem243 { get; set; }
        public string? MessageFromSourceSystem244 { get; set; }
        public string? MessageFromSourceSystem245 { get; set; }
        public string? MessageFromSourceSystem246 { get; set; }
        public string? MessageFromSourceSystem247 { get; set; }
        public string? MessageFromSourceSystem248 { get; set; }
        public string? MessageFromSourceSystem249 { get; set; }
        public string? MessageFromSourceSystem250 { get; set; }
        public string? MessageFromSourceSystem251 { get; set; }
        public string? MessageFromSourceSystem252 { get; set; }
        public string? MessageFromSourceSystem253 { get; set; }
        public string? MessageFromSourceSystem254 { get; set; }
        public string? MessageFromSourceSystem255 { get; set; }
        public string? MessageFromSourceSystem256 { get; set; }
        public string? MessageFromSourceSystem257 { get; set; }
        public string? MessageFromSourceSystem258 { get; set; }
        public string? MessageFromSourceSystem259 { get; set; }
        public string? MessageFromSourceSystem260 { get; set; }
        public string? MessageFromSourceSystem261 { get; set; }
        public string? MessageFromSourceSystem262 { get; set; }
        public string? MessageFromSourceSystem263 { get; set; }
        public string? MessageFromSourceSystem264 { get; set; }
        public string? MessageFromSourceSystem265 { get; set; }
        public string? MessageFromSourceSystem266 { get; set; }
        public string? MessageFromSourceSystem267 { get; set; }
        public string? MessageFromSourceSystem268 { get; set; }
        public string? MessageFromSourceSystem269 { get; set; }
        public string? MessageFromSourceSystem270 { get; set; }
        public string? MessageFromSourceSystem271 { get; set; }
        public string? MessageFromSourceSystem272 { get; set; }
        public string? MessageFromSourceSystem273 { get; set; }
        public string? MessageFromSourceSystem274 { get; set; }
        public string? MessageFromSourceSystem275 { get; set; }
        public string? MessageFromSourceSystem276 { get; set; }
        public string? MessageFromSourceSystem277 { get; set; }
        public string? MessageFromSourceSystem278 { get; set; }
        public string? MessageFromSourceSystem279 { get; set; }
        public string? MessageFromSourceSystem280 { get; set; }
        public string? MessageFromSourceSystem281 { get; set; }
        public string? MessageFromSourceSystem282 { get; set; }
        public string? MessageFromSourceSystem283 { get; set; }
        public string? MessageFromSourceSystem284 { get; set; }
        public string? MessageFromSourceSystem285 { get; set; }
        public string? MessageFromSourceSystem286 { get; set; }
        public string? MessageFromSourceSystem287 { get; set; }
        public string? MessageFromSourceSystem288 { get; set; }
        public string? MessageFromSourceSystem289 { get; set; }
        public string? MessageFromSourceSystem290 { get; set; }
        public string? MessageFromSourceSystem291 { get; set; }
        public string? MessageFromSourceSystem292 { get; set; }
        public string? MessageFromSourceSystem293 { get; set; }
        public string? MessageFromSourceSystem294 { get; set; }
        public string? MessageFromSourceSystem295 { get; set; }
        public string? MessageFromSourceSystem296 { get; set; }
        public string? MessageFromSourceSystem297 { get; set; }
        public string? MessageFromSourceSystem298 { get; set; }
        public string? MessageFromSourceSystem299 { get; set; }
        public string? MessageFromSourceSystem300 { get; set; }
        public string? MessageFromSourceSystem301 { get; set; }
        public string? MessageFromSourceSystem302 { get; set; }
        public string? MessageFromSourceSystem303 { get; set; }
        public string? MessageFromSourceSystem304 { get; set; }
        public string? MessageFromSourceSystem305 { get; set; }
        public string? MessageFromSourceSystem306 { get; set; }

    }

    public class MessageReplyObject
    {
        public string? Id { get; set; }
        public string? Message { get; set; }
        public string? MessageId { get; set; }
        public string? MessageType { get; set; }
        public string? MessagePub { get; set; }
        public string? MessageExp { get; set; }

        public string? MessageFromSourceSystem7 { get; set; }
        public string? MessageFromSourceSystem8 { get; set; }
        public string? MessageFromSourceSystem9 { get; set; }
        public string? MessageFromSourceSystem10 { get; set; }
        public string? MessageFromSourceSystem11 { get; set; }
        public string? MessageFromSourceSystem12 { get; set; }
        public string? MessageFromSourceSystem13 { get; set; }
        public string? MessageFromSourceSystem14 { get; set; }
        public string? MessageFromSourceSystem15 { get; set; }
        public string? MessageFromSourceSystem16 { get; set; }
        public string? MessageFromSourceSystem17 { get; set; }
        public string? MessageFromSourceSystem18 { get; set; }
        public string? MessageFromSourceSystem19 { get; set; }
        public string? MessageFromSourceSystem20 { get; set; }
        public string? MessageFromSourceSystem21 { get; set; }
        public string? MessageFromSourceSystem22 { get; set; }
        public string? MessageFromSourceSystem23 { get; set; }
        public string? MessageFromSourceSystem24 { get; set; }
        public string? MessageFromSourceSystem25 { get; set; }
        public string? MessageFromSourceSystem26 { get; set; }
        public string? MessageFromSourceSystem27 { get; set; }
        public string? MessageFromSourceSystem28 { get; set; }
        public string? MessageFromSourceSystem29 { get; set; }
        public string? MessageFromSourceSystem30 { get; set; }
        public string? MessageFromSourceSystem31 { get; set; }
        public string? MessageFromSourceSystem32 { get; set; }
        public string? MessageFromSourceSystem33 { get; set; }
        public string? MessageFromSourceSystem34 { get; set; }
        public string? MessageFromSourceSystem35 { get; set; }
        public string? MessageFromSourceSystem36 { get; set; }
        public string? MessageFromSourceSystem37 { get; set; }
        public string? MessageFromSourceSystem38 { get; set; }
        public string? MessageFromSourceSystem39 { get; set; }
        public string? MessageFromSourceSystem40 { get; set; }
        public string? MessageFromSourceSystem41 { get; set; }
        public string? MessageFromSourceSystem42 { get; set; }
        public string? MessageFromSourceSystem43 { get; set; }
        public string? MessageFromSourceSystem44 { get; set; }
        public string? MessageFromSourceSystem45 { get; set; }
        public string? MessageFromSourceSystem46 { get; set; }
        public string? MessageFromSourceSystem47 { get; set; }
        public string? MessageFromSourceSystem48 { get; set; }
        public string? MessageFromSourceSystem49 { get; set; }
        public string? MessageFromSourceSystem50 { get; set; }
        public string? MessageFromSourceSystem51 { get; set; }
        public string? MessageFromSourceSystem52 { get; set; }
        public string? MessageFromSourceSystem53 { get; set; }
        public string? MessageFromSourceSystem54 { get; set; }
        public string? MessageFromSourceSystem55 { get; set; }
        public string? MessageFromSourceSystem56 { get; set; }
        public string? MessageFromSourceSystem57 { get; set; }
        public string? MessageFromSourceSystem58 { get; set; }
        public string? MessageFromSourceSystem59 { get; set; }
        public string? MessageFromSourceSystem60 { get; set; }
        public string? MessageFromSourceSystem61 { get; set; }
        public string? MessageFromSourceSystem62 { get; set; }
        public string? MessageFromSourceSystem63 { get; set; }
        public string? MessageFromSourceSystem64 { get; set; }
        public string? MessageFromSourceSystem65 { get; set; }
        public string? MessageFromSourceSystem66 { get; set; }
        public string? MessageFromSourceSystem67 { get; set; }
        public string? MessageFromSourceSystem68 { get; set; }
        public string? MessageFromSourceSystem69 { get; set; }
        public string? MessageFromSourceSystem70 { get; set; }
        public string? MessageFromSourceSystem71 { get; set; }
        public string? MessageFromSourceSystem72 { get; set; }
        public string? MessageFromSourceSystem73 { get; set; }
        public string? MessageFromSourceSystem74 { get; set; }
        public string? MessageFromSourceSystem75 { get; set; }
        public string? MessageFromSourceSystem76 { get; set; }
        public string? MessageFromSourceSystem77 { get; set; }
        public string? MessageFromSourceSystem78 { get; set; }
        public string? MessageFromSourceSystem79 { get; set; }
        public string? MessageFromSourceSystem80 { get; set; }
        public string? MessageFromSourceSystem81 { get; set; }
        public string? MessageFromSourceSystem82 { get; set; }
        public string? MessageFromSourceSystem83 { get; set; }
        public string? MessageFromSourceSystem84 { get; set; }
        public string? MessageFromSourceSystem85 { get; set; }
        public string? MessageFromSourceSystem86 { get; set; }
        public string? MessageFromSourceSystem87 { get; set; }
        public string? MessageFromSourceSystem88 { get; set; }
        public string? MessageFromSourceSystem89 { get; set; }
        public string? MessageFromSourceSystem90 { get; set; }
        public string? MessageFromSourceSystem91 { get; set; }
        public string? MessageFromSourceSystem92 { get; set; }
        public string? MessageFromSourceSystem93 { get; set; }
        public string? MessageFromSourceSystem94 { get; set; }
        public string? MessageFromSourceSystem95 { get; set; }
        public string? MessageFromSourceSystem96 { get; set; }
        public string? MessageFromSourceSystem97 { get; set; }
        public string? MessageFromSourceSystem98 { get; set; }
        public string? MessageFromSourceSystem99 { get; set; }
        public string? MessageFromSourceSystem100 { get; set; }
        public string? MessageFromSourceSystem101 { get; set; }
        public string? MessageFromSourceSystem102 { get; set; }
        public string? MessageFromSourceSystem103 { get; set; }
        public string? MessageFromSourceSystem104 { get; set; }
        public string? MessageFromSourceSystem105 { get; set; }
        public string? MessageFromSourceSystem106 { get; set; }
        public string? MessageFromSourceSystem107 { get; set; }
        public string? MessageFromSourceSystem108 { get; set; }
        public string? MessageFromSourceSystem109 { get; set; }
        public string? MessageFromSourceSystem110 { get; set; }
        public string? MessageFromSourceSystem111 { get; set; }
        public string? MessageFromSourceSystem112 { get; set; }
        public string? MessageFromSourceSystem113 { get; set; }
        public string? MessageFromSourceSystem114 { get; set; }
        public string? MessageFromSourceSystem115 { get; set; }
        public string? MessageFromSourceSystem116 { get; set; }
        public string? MessageFromSourceSystem117 { get; set; }
        public string? MessageFromSourceSystem118 { get; set; }
        public string? MessageFromSourceSystem119 { get; set; }
        public string? MessageFromSourceSystem120 { get; set; }
        public string? MessageFromSourceSystem121 { get; set; }
        public string? MessageFromSourceSystem122 { get; set; }
        public string? MessageFromSourceSystem123 { get; set; }
        public string? MessageFromSourceSystem124 { get; set; }
        public string? MessageFromSourceSystem125 { get; set; }
        public string? MessageFromSourceSystem126 { get; set; }
        public string? MessageFromSourceSystem127 { get; set; }
        public string? MessageFromSourceSystem128 { get; set; }
        public string? MessageFromSourceSystem129 { get; set; }
        public string? MessageFromSourceSystem130 { get; set; }
        public string? MessageFromSourceSystem131 { get; set; }
        public string? MessageFromSourceSystem132 { get; set; }
        public string? MessageFromSourceSystem133 { get; set; }
        public string? MessageFromSourceSystem134 { get; set; }
        public string? MessageFromSourceSystem135 { get; set; }
        public string? MessageFromSourceSystem136 { get; set; }
        public string? MessageFromSourceSystem137 { get; set; }
        public string? MessageFromSourceSystem138 { get; set; }
        public string? MessageFromSourceSystem139 { get; set; }
        public string? MessageFromSourceSystem140 { get; set; }
        public string? MessageFromSourceSystem141 { get; set; }
        public string? MessageFromSourceSystem142 { get; set; }
        public string? MessageFromSourceSystem143 { get; set; }
        public string? MessageFromSourceSystem144 { get; set; }
        public string? MessageFromSourceSystem145 { get; set; }
        public string? MessageFromSourceSystem146 { get; set; }
        public string? MessageFromSourceSystem147 { get; set; }
        public string? MessageFromSourceSystem148 { get; set; }
        public string? MessageFromSourceSystem149 { get; set; }
        public string? MessageFromSourceSystem150 { get; set; }
        public string? MessageFromSourceSystem151 { get; set; }
        public string? MessageFromSourceSystem152 { get; set; }
        public string? MessageFromSourceSystem153 { get; set; }
        public string? MessageFromSourceSystem154 { get; set; }
        public string? MessageFromSourceSystem155 { get; set; }
        public string? MessageFromSourceSystem156 { get; set; }
        public string? MessageFromSourceSystem157 { get; set; }
        public string? MessageFromSourceSystem158 { get; set; }
        public string? MessageFromSourceSystem159 { get; set; }
        public string? MessageFromSourceSystem160 { get; set; }
        public string? MessageFromSourceSystem161 { get; set; }
        public string? MessageFromSourceSystem162 { get; set; }
        public string? MessageFromSourceSystem163 { get; set; }
        public string? MessageFromSourceSystem164 { get; set; }
        public string? MessageFromSourceSystem165 { get; set; }
        public string? MessageFromSourceSystem166 { get; set; }
        public string? MessageFromSourceSystem167 { get; set; }
        public string? MessageFromSourceSystem168 { get; set; }
        public string? MessageFromSourceSystem169 { get; set; }
        public string? MessageFromSourceSystem170 { get; set; }
        public string? MessageFromSourceSystem171 { get; set; }
        public string? MessageFromSourceSystem172 { get; set; }
        public string? MessageFromSourceSystem173 { get; set; }
        public string? MessageFromSourceSystem174 { get; set; }
        public string? MessageFromSourceSystem175 { get; set; }
        public string? MessageFromSourceSystem176 { get; set; }
        public string? MessageFromSourceSystem177 { get; set; }
        public string? MessageFromSourceSystem178 { get; set; }
        public string? MessageFromSourceSystem179 { get; set; }
        public string? MessageFromSourceSystem180 { get; set; }
        public string? MessageFromSourceSystem181 { get; set; }
        public string? MessageFromSourceSystem182 { get; set; }
        public string? MessageFromSourceSystem183 { get; set; }
        public string? MessageFromSourceSystem184 { get; set; }
        public string? MessageFromSourceSystem185 { get; set; }
        public string? MessageFromSourceSystem186 { get; set; }
        public string? MessageFromSourceSystem187 { get; set; }
        public string? MessageFromSourceSystem188 { get; set; }
        public string? MessageFromSourceSystem189 { get; set; }
        public string? MessageFromSourceSystem190 { get; set; }
        public string? MessageFromSourceSystem191 { get; set; }
        public string? MessageFromSourceSystem192 { get; set; }
        public string? MessageFromSourceSystem193 { get; set; }
        public string? MessageFromSourceSystem194 { get; set; }
        public string? MessageFromSourceSystem195 { get; set; }
        public string? MessageFromSourceSystem196 { get; set; }
        public string? MessageFromSourceSystem197 { get; set; }
        public string? MessageFromSourceSystem198 { get; set; }
        public string? MessageFromSourceSystem199 { get; set; }
        public string? MessageFromSourceSystem200 { get; set; }
        public string? MessageFromSourceSystem201 { get; set; }
        public string? MessageFromSourceSystem202 { get; set; }
        public string? MessageFromSourceSystem203 { get; set; }
        public string? MessageFromSourceSystem204 { get; set; }
        public string? MessageFromSourceSystem205 { get; set; }
        public string? MessageFromSourceSystem206 { get; set; }
        public string? MessageFromSourceSystem207 { get; set; }
        public string? MessageFromSourceSystem208 { get; set; }
        public string? MessageFromSourceSystem209 { get; set; }
        public string? MessageFromSourceSystem210 { get; set; }
        public string? MessageFromSourceSystem211 { get; set; }
        public string? MessageFromSourceSystem212 { get; set; }
        public string? MessageFromSourceSystem213 { get; set; }
        public string? MessageFromSourceSystem214 { get; set; }
        public string? MessageFromSourceSystem215 { get; set; }
        public string? MessageFromSourceSystem216 { get; set; }
        public string? MessageFromSourceSystem217 { get; set; }
        public string? MessageFromSourceSystem218 { get; set; }
        public string? MessageFromSourceSystem219 { get; set; }
        public string? MessageFromSourceSystem220 { get; set; }
        public string? MessageFromSourceSystem221 { get; set; }
        public string? MessageFromSourceSystem222 { get; set; }
        public string? MessageFromSourceSystem223 { get; set; }
        public string? MessageFromSourceSystem224 { get; set; }
        public string? MessageFromSourceSystem225 { get; set; }
        public string? MessageFromSourceSystem226 { get; set; }
        public string? MessageFromSourceSystem227 { get; set; }
        public string? MessageFromSourceSystem228 { get; set; }
        public string? MessageFromSourceSystem229 { get; set; }
        public string? MessageFromSourceSystem230 { get; set; }
        public string? MessageFromSourceSystem231 { get; set; }
        public string? MessageFromSourceSystem232 { get; set; }
        public string? MessageFromSourceSystem233 { get; set; }
        public string? MessageFromSourceSystem234 { get; set; }
        public string? MessageFromSourceSystem235 { get; set; }
        public string? MessageFromSourceSystem236 { get; set; }
        public string? MessageFromSourceSystem237 { get; set; }
        public string? MessageFromSourceSystem238 { get; set; }
        public string? MessageFromSourceSystem239 { get; set; }
        public string? MessageFromSourceSystem240 { get; set; }
        public string? MessageFromSourceSystem241 { get; set; }
        public string? MessageFromSourceSystem242 { get; set; }
        public string? MessageFromSourceSystem243 { get; set; }
        public string? MessageFromSourceSystem244 { get; set; }
        public string? MessageFromSourceSystem245 { get; set; }
        public string? MessageFromSourceSystem246 { get; set; }
        public string? MessageFromSourceSystem247 { get; set; }
        public string? MessageFromSourceSystem248 { get; set; }
        public string? MessageFromSourceSystem249 { get; set; }
        public string? MessageFromSourceSystem250 { get; set; }
        public string? MessageFromSourceSystem251 { get; set; }
        public string? MessageFromSourceSystem252 { get; set; }
        public string? MessageFromSourceSystem253 { get; set; }
        public string? MessageFromSourceSystem254 { get; set; }
        public string? MessageFromSourceSystem255 { get; set; }
        public string? MessageFromSourceSystem256 { get; set; }
        public string? MessageFromSourceSystem257 { get; set; }
        public string? MessageFromSourceSystem258 { get; set; }
        public string? MessageFromSourceSystem259 { get; set; }
        public string? MessageFromSourceSystem260 { get; set; }
        public string? MessageFromSourceSystem261 { get; set; }
        public string? MessageFromSourceSystem262 { get; set; }
        public string? MessageFromSourceSystem263 { get; set; }
        public string? MessageFromSourceSystem264 { get; set; }
        public string? MessageFromSourceSystem265 { get; set; }
        public string? MessageFromSourceSystem266 { get; set; }
        public string? MessageFromSourceSystem267 { get; set; }
        public string? MessageFromSourceSystem268 { get; set; }
        public string? MessageFromSourceSystem269 { get; set; }
        public string? MessageFromSourceSystem270 { get; set; }
        public string? MessageFromSourceSystem271 { get; set; }
        public string? MessageFromSourceSystem272 { get; set; }
        public string? MessageFromSourceSystem273 { get; set; }
        public string? MessageFromSourceSystem274 { get; set; }
        public string? MessageFromSourceSystem275 { get; set; }
        public string? MessageFromSourceSystem276 { get; set; }
        public string? MessageFromSourceSystem277 { get; set; }
        public string? MessageFromSourceSystem278 { get; set; }
        public string? MessageFromSourceSystem279 { get; set; }
        public string? MessageFromSourceSystem280 { get; set; }
        public string? MessageFromSourceSystem281 { get; set; }
        public string? MessageFromSourceSystem282 { get; set; }
        public string? MessageFromSourceSystem283 { get; set; }
        public string? MessageFromSourceSystem284 { get; set; }
        public string? MessageFromSourceSystem285 { get; set; }
        public string? MessageFromSourceSystem286 { get; set; }
        public string? MessageFromSourceSystem287 { get; set; }
        public string? MessageFromSourceSystem288 { get; set; }
        public string? MessageFromSourceSystem289 { get; set; }
        public string? MessageFromSourceSystem290 { get; set; }
        public string? MessageFromSourceSystem291 { get; set; }
        public string? MessageFromSourceSystem292 { get; set; }
        public string? MessageFromSourceSystem293 { get; set; }
        public string? MessageFromSourceSystem294 { get; set; }
        public string? MessageFromSourceSystem295 { get; set; }
        public string? MessageFromSourceSystem296 { get; set; }
        public string? MessageFromSourceSystem297 { get; set; }
        public string? MessageFromSourceSystem298 { get; set; }
        public string? MessageFromSourceSystem299 { get; set; }
        public string? MessageFromSourceSystem300 { get; set; }
        public string? MessageFromSourceSystem301 { get; set; }
        public string? MessageFromSourceSystem302 { get; set; }
        public string? MessageFromSourceSystem303 { get; set; }
        public string? MessageFromSourceSystem304 { get; set; }
        public string? MessageFromSourceSystem305 { get; set; }
        public string? MessageFromSourceSystem306 { get; set; }

    }
}